"""Changes in models

Revision ID: 0afccd2ce3d1
Revises: 
Create Date: 2023-12-13 22:27:03.548804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0afccd2ce3d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advocate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advocate', schema=None) as batch_op:
        batch_op.drop_column('verified')
        batch_op.drop_column('resume')

    # ### end Alembic commands ###
