"""Migration 2

Revision ID: 32496e852f05
Revises: ae7196bc8e49
Create Date: 2023-12-15 22:58:32.592738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32496e852f05'
down_revision = 'ae7196bc8e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('law_catg_benf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('law_catg_benf', schema=None) as batch_op:
        batch_op.drop_column('doc_name')

    # ### end Alembic commands ###
