"""Foreign keys for law category table

Revision ID: 87ff9cc10acc
Revises: 32496e852f05
Create Date: 2023-12-16 22:46:52.183508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ff9cc10acc'
down_revision = '32496e852f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('law_catg_benf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('advocate_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key('advocate_id', 'advocate', ['advocate_id'], ['advocate_id'])
        batch_op.create_foreign_key('user_id', 'user', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('law_catg_benf', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('date_created')
        batch_op.drop_column('advocate_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
