"""new column advocate

Revision ID: 8c261c64619f
Revises: 6e9a37ae9e07
Create Date: 2023-12-20 03:14:38.384620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c261c64619f'
down_revision = '6e9a37ae9e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advocate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_cost_per_hr', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advocate', schema=None) as batch_op:
        batch_op.drop_column('min_cost_per_hr')

    # ### end Alembic commands ###
