"""empty message

Revision ID: ae7196bc8e49
Revises: 0afccd2ce3d1
Create Date: 2023-12-15 22:55:31.310274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7196bc8e49'
down_revision = '0afccd2ce3d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('law_catg_benf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('beneficiaries', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('law_catg_benf')
    # ### end Alembic commands ###
